### ISSUE TITLE
Migrate from eslint-plugin-node to eslint-plugin-n

### ISSUE THREAD

**Issue by Alonski** [CrowdStrike/eslint-config-crowdstrike#84]
eslint-plugin-node is no longer maintained:
https://github.com/mysticatea/eslint-plugin-node/issues/300

The successor is eslint-plugin-n:
https://github.com/eslint-community/eslint-plugin-n

We should migrate this package to use eslint-plugin-n and release a breaking change.
Then upgrade upstream packages/monorepo.

Similar issue: https://github.com/CrowdStrike/eslint-config-crowdstrike-node/issues/81

**Comment by Charlie-Crowdstrike** [comment]
https://github.com/CrowdStrike/eslint-config-crowdstrike/pull/92

**Comment by kellyselden** [comment]
This package doesn't involve eslint-plugin-node.
